import { PortfolioData } from "./types";

export const INITIAL_PORTFOLIO_DATA: PortfolioData = {
  name: "Sirigiri Anand Kumar",
  university: "REVA University",
  degree: "B.Tech",
  branch: "Computer Science and Information Technology (CSIT)",
  bio: "An enthusiastic Undergraduate Computer Science & Information Technology student at REVA University. Driven by open-source contribution, problem-solving in DSA with Java, and exploring the frontiers of Generative AI Prompt Engineering.",
  email: "anandsirigiri2006@gmail.com",
  phone: "8618636854",
  githubUsername: "Anandsirigiri07",
  linkedinUrl: "https://www.linkedin.com/in/anand-sirigiri-a91910368/",
  leetcodeUsername: "Anand_sirigiri07",
  hack2skillUsername: "Anandsirigiri07",
  statsOverrides: {
    githubRepos: 14,
    githubFollowers: 5,
    githubStars: 1,
    leetcodeSolved: 42,
    leetcodeRanking: 450000,
    hack2skillRank: 120,
    hack2skillScore: 850,
    hack2skillPrompts: 15,
  },
  achievements: [
    {
      id: "ach-1",
      date: "May 2024",
      title: "GSSoC Contributor",
      description: "Actively contributed to open-source software, solved issues, and merged Pull Requests under the GirlScript Summer of Code (GSSoC) program.",
      proofLink: "https://github.com/Anandsirigiri07",
      badge: "GSSoC '24 Contributor Badge",
      category: "Open Source",
      archived: false,
      displayOrder: 1,
    },
    {
      id: "ach-2",
      date: "April 2024",
      title: "Hack2Skill Prompt War Contributor",
      description: "Participated and contributed to the Hack2Skill Prompt War competition, designing innovative LLM instructions and experimenting with system prompt design.",
      proofLink: "https://hack2skill.com/",
      badge: "Prompt War Contributor",
      category: "Competitions",
      archived: false,
      displayOrder: 2,
    },
  ],
  projects: [
    {
      id: "proj-1",
      title: "Java DSA Implementation Sandbox",
      overview: "A dedicated repository practicing foundational and intermediate data structures and algorithms using Java. Implements custom list architectures, array operations, and standard sorting/searching logic.",
      problemStatement: "Bridging the gap between conceptual algorithm workflows and clean, modular Java syntax for a beginner developer.",
      solution: "Developed custom-implemented arrays, bubble-sort, selection-sort, and search engines with comprehensive console tracing for learning.",
      technologies: ["Java", "Data Structures", "Algorithms"],
      githubLink: "https://github.com/Anandsirigiri07",
      learningOutcomes: "Learned Java memory allocation, syntax rules, class designs, time complexity bounds, and direct problem-solving.",
      date: "Jan 2024",
    },
    {
      id: "proj-2",
      title: "C Foundational Utilities Suite",
      overview: "A collection of computational utilities, mathematical matrix tools, and binary file handlers built during undergraduate REVA lab assignments.",
      problemStatement: "Configuring memory management, pointers, and performance-critical operations cleanly within C programming environments.",
      solution: "Engineered a set of optimized console utilities demonstrating pointer math, structure variables, and binary standard input-output operations.",
      technologies: ["C Programming", "GDB Debugger", "Pointer Arithmetic"],
      githubLink: "https://github.com/Anandsirigiri07",
      learningOutcomes: "Mastered memory allocation using malloc/calloc, stack frames, pointer manipulation, and GCC debugging.",
      date: "Nov 2023",
    },
  ],
  certifications: [
    {
      id: "cert-1",
      name: "B.Tech Computer Science Foundations Certificate",
      issuer: "REVA University",
      date: "June 2024",
      proofLink: "https://www.reva.edu.in/",
    },
  ],
  skills: [
    {
      id: "sk-1",
      name: "C Programming",
      level: 80,
      phase: "C Programming",
      status: "Mastered",
    },
    {
      id: "sk-2",
      name: "Java Basics",
      level: 60,
      phase: "Java Basics",
      status: "In Progress",
    },
    {
      id: "sk-3",
      name: "Object-Oriented Programming (Java)",
      level: 40,
      phase: "OOP",
      status: "In Progress",
    },
    {
      id: "sk-4",
      name: "Data Structures & Algorithms (Basics)",
      level: 25,
      phase: "DSA",
      status: "In Progress",
    },
    {
      id: "sk-5",
      name: "Web Development Foundations (HTML/CSS/JS)",
      level: 15,
      phase: "Web Dev",
      status: "Planned",
    },
    {
      id: "sk-6",
      name: "Advanced Frameworks & Integrations",
      level: 5,
      phase: "Advanced Tech",
      status: "Planned",
    },
  ],
  timeline: [
    {
      id: "t-1",
      year: "Year 1",
      title: "Foundations & Open Source Exploration",
      status: "Completed",
      description: "Acclimatized to Computer Science fundamentals, mastered C programming structures, and initiated direct open-source contributions through GirlScript Summer of Code.",
      date: "2025 - 2026",
      items: [
        "Enrolled in REVA University CSIT program, maintaining high academic focus.",
        "Mastered basic C constructs and algorithms during university labs.",
        "Contributed to multiple real open-source codes under GSSoC '24.",
        "Experimented with LLM system tuning in Hack2Skill Prompt War."
      ],
    },
    {
      id: "t-2",
      year: "Year 2",
      title: "Core Java & DSA Deep Dive",
      status: "Current",
      description: "Focusing heavily on object-oriented software engineering principles in Java, solving algorithmic problems on LeetCode, and building client-side modular packages.",
      date: "2026 - 2027",
      items: [
        "Active learning of Java object workflows and classes.",
        "Solving beginner to intermediate problems consistently on LeetCode.",
        "Exploring full-stack design patterns with Express and Node.js.",
        "Pre-selecting elective studies for advanced cloud architectures."
      ],
    },
    {
      id: "t-3",
      year: "Year 3",
      title: "Advanced Full-Stack Products & Internships",
      status: "Future",
      description: "Mastering advanced tools (such as NestJS, Next.js, and cloud systems), building robust deployment projects, and pursuing industry positions.",
      date: "2027 - 2028",
      items: [
        "Aiming for internships in systems development or web-scale software houses.",
        "Solving 300+ advanced LeetCode algorithms with recursive and dynamic planning.",
        "Building end-to-end fullstack apps with cloud databases (like PostgreSQL).",
        "Participating in prominent national and college hackathons."
      ],
    },
    {
      id: "t-4",
      year: "Year 4",
      title: "Research, Capstone, & Software Engineer Placement",
      status: "Future",
      description: "Publishing a research milestone or capstone project, contributing to prominent developer communities, and securing a top-tier software placement.",
      date: "2028 - 2029",
      items: [
        "Synthesizing high-quality B.Tech capstone project combining AI with scalable engineering.",
        "Preparing completely for corporate recruitment rounds.",
        "Mentoring first-year REVA University CSIT juniors in DSA and open-source contributions."
      ],
    },
  ],
};
